[2025-02-21T22:20:20.897+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_data_dag.say_hello manual__2025-02-21T22:20:12.067496+00:00 [queued]>
[2025-02-21T22:20:20.905+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_data_dag.say_hello manual__2025-02-21T22:20:12.067496+00:00 [queued]>
[2025-02-21T22:20:20.906+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T22:20:20.988+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): say_hello> on 2025-02-21 22:20:12.067496+00:00
[2025-02-21T22:20:20.992+0000] {standard_task_runner.py:57} INFO - Started process 135 to run task
[2025-02-21T22:20:20.995+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_data_dag', 'say_hello', 'manual__2025-02-21T22:20:12.067496+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp9n37ir16']
[2025-02-21T22:20:20.997+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask say_hello
[2025-02-21T22:20:21.060+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_data_dag.say_hello manual__2025-02-21T22:20:12.067496+00:00 [running]> on host 7c80cef5d079
[2025-02-21T22:20:21.143+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_data_dag' AIRFLOW_CTX_TASK_ID='say_hello' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T22:20:12.067496+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T22:20:12.067496+00:00'
[2025-02-21T22:20:21.145+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-21T22:20:21.146+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec scraper python /app/scraper.py']
[2025-02-21T22:20:21.152+0000] {subprocess.py:86} INFO - Output:
[2025-02-21T22:20:21.195+0000] {subprocess.py:93} INFO - Error response from daemon: Container be5ac2ab9a1747d9b046d73ae6a58cd375888da975799ad4901c291385ce34c7 is restarting, wait until the container is running
[2025-02-21T22:20:21.198+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-21T22:20:21.211+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T22:20:21.214+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=gold_data_dag, task_id=say_hello, execution_date=20250221T222012, start_date=20250221T222020, end_date=20250221T222021
[2025-02-21T22:20:21.227+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 14 for task say_hello (Bash command failed. The command returned a non-zero exit code 1.; 135)
[2025-02-21T22:20:21.249+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-21T22:20:21.266+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
