[2025-02-26T20:24:22.533+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:24:22.595+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:24:22.599+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-26T20:24:22.688+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce> on 2025-01-14 00:00:00+00:00
[2025-02-26T20:24:22.718+0000] {standard_task_runner.py:57} INFO - Started process 1055 to run task
[2025-02-26T20:24:22.742+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'run_mapreduce', 'scheduled__2025-01-14T00:00:00+00:00', '--job-id', '115', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp6dernevb']
[2025-02-26T20:24:22.753+0000] {standard_task_runner.py:85} INFO - Job 115: Subtask run_mapreduce
[2025-02-26T20:24:23.051+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-14T00:00:00+00:00 [running]> on host c96a1011f5a3
[2025-02-26T20:24:23.471+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-14T00:00:00+00:00'
[2025-02-26T20:24:23.478+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T20:24:23.487+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i -u root namenode bash -c \'         cd /tmp &&         cp /mnt/hadoop_data/mapreduce/mapper.py . &&         cp /mnt/hadoop_data/mapreduce/reducer.py . &&         chmod +x mapper.py reducer.py &&         hdfs dfs -rm -r hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=14 || true &&         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -files mapper.py,reducer.py         -mapper "python mapper.py"         -reducer "python reducer.py"         -input hdfs:///user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=14/yfinance_raw.json         -output hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=14\'\n        ']
[2025-02-26T20:24:23.543+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T20:24:40.683+0000] {subprocess.py:93} INFO - rm: `hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=14': No such file or directory
[2025-02-26T20:24:54.631+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:54,628 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-26T20:24:55.465+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:55,460 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-26T20:24:55.132+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:55,460 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-26T20:24:54.663+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:54,658 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-26T20:24:55.960+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:55,958 INFO mapreduce.JobSubmitter: Cleaning up the staging area file:/tmp/hadoop/mapred/staging/root1928193045/.staging/job_local1928193045_0001
[2025-02-26T20:24:55.963+0000] {subprocess.py:93} INFO - 2025-02-26 20:24:55,962 ERROR streaming.StreamJob: Error Launching job : Input path does not exist: hdfs:/user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=14/yfinance_raw.json
[2025-02-26T20:24:55.965+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-26T20:24:56.517+0000] {subprocess.py:97} INFO - Command exited with return code 5
[2025-02-26T20:24:56.563+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-26T20:24:56.585+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=run_mapreduce, execution_date=20250114T000000, start_date=20250226T202422, end_date=20250226T202456
[2025-02-26T20:24:56.687+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 115 for task run_mapreduce (Bash command failed. The command returned a non-zero exit code 5.; 1055)
[2025-02-26T20:24:57.154+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:24:57.201+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:37:26.262+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:37:26.314+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-14T00:00:00+00:00 [queued]>
[2025-02-26T20:37:26.319+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-26T20:37:26.379+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce> on 2025-01-14 00:00:00+00:00
[2025-02-26T20:37:26.405+0000] {standard_task_runner.py:57} INFO - Started process 254 to run task
[2025-02-26T20:37:26.440+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'run_mapreduce', 'scheduled__2025-01-14T00:00:00+00:00', '--job-id', '214', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpqobf5p3_']
[2025-02-26T20:37:26.452+0000] {standard_task_runner.py:85} INFO - Job 214: Subtask run_mapreduce
[2025-02-26T20:37:26.763+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-14T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:37:27.336+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-01-14T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-14T00:00:00+00:00'
[2025-02-26T20:37:27.341+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T20:37:27.343+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i -u root namenode bash -c \'         cd /tmp &&         cp /mnt/hadoop_data/mapreduce/mapper.py . &&         cp /mnt/hadoop_data/mapreduce/reducer.py . &&         chmod +x mapper.py reducer.py &&         hdfs dfs -rm -r hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=14 || true &&         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -files mapper.py,reducer.py         -mapper "python mapper.py"         -reducer "python reducer.py"         -input hdfs:///user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=14/yfinance_raw.json         -output hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=14\'\n        ']
[2025-02-26T20:37:27.377+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T20:37:44.703+0000] {subprocess.py:93} INFO - rm: `hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=14': No such file or directory
[2025-02-26T20:38:03.050+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:03,026 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-26T20:38:03.901+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:03,899 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-26T20:38:03.902+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:03,900 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-26T20:38:04.282+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:04,271 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-26T20:38:10.719+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:10,717 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-26T20:38:14.243+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:14,240 INFO mapreduce.JobSubmitter: number of splits:1
[2025-02-26T20:38:18.839+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:18,831 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_local1833577736_0001
[2025-02-26T20:38:18.840+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:18,835 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-26T20:38:28.464+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:28,438 INFO mapred.LocalDistributedCacheManager: Localized file:/tmp/mapper.py as file:/tmp/hadoop-root/mapred/local/job_local1833577736_0001_345e6d86-cd1a-4aec-9e7f-14a84cf24112/mapper.py
[2025-02-26T20:38:28.903+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:28,806 INFO mapred.LocalDistributedCacheManager: Localized file:/tmp/reducer.py as file:/tmp/hadoop-root/mapred/local/job_local1833577736_0001_3bc1074f-845b-4517-8806-40906aa86072/reducer.py
[2025-02-26T20:38:45.265+0000] {subprocess.py:97} INFO - Command exited with return code 137
[2025-02-26T20:38:45.538+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 137.
[2025-02-26T20:38:45.577+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=run_mapreduce, execution_date=20250114T000000, start_date=20250226T203726, end_date=20250226T203845
[2025-02-26T20:38:45.745+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 214 for task run_mapreduce (Bash command failed. The command returned a non-zero exit code 137.; 254)
[2025-02-26T20:38:45.844+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:38:46.053+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
