[2025-02-21T22:09:01.837+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_data_dag.say_hello manual__2025-02-21T22:08:53.325551+00:00 [queued]>
[2025-02-21T22:09:01.849+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_data_dag.say_hello manual__2025-02-21T22:08:53.325551+00:00 [queued]>
[2025-02-21T22:09:01.851+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T22:09:01.867+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): say_hello> on 2025-02-21 22:08:53.325551+00:00
[2025-02-21T22:09:01.872+0000] {standard_task_runner.py:57} INFO - Started process 181 to run task
[2025-02-21T22:09:01.876+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_data_dag', 'say_hello', 'manual__2025-02-21T22:08:53.325551+00:00', '--job-id', '9', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpf90m90p_']
[2025-02-21T22:09:01.879+0000] {standard_task_runner.py:85} INFO - Job 9: Subtask say_hello
[2025-02-21T22:09:01.940+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_data_dag.say_hello manual__2025-02-21T22:08:53.325551+00:00 [running]> on host 7c80cef5d079
[2025-02-21T22:09:02.138+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_data_dag' AIRFLOW_CTX_TASK_ID='say_hello' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T22:08:53.325551+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T22:08:53.325551+00:00'
[2025-02-21T22:09:02.140+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-21T22:09:02.142+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker exec scraper python /app/scraper.py']
[2025-02-21T22:09:02.155+0000] {subprocess.py:86} INFO - Output:
[2025-02-21T22:09:02.206+0000] {subprocess.py:93} INFO - Error response from daemon: Container 035a6a624fcec960eca1fff9dd1b9c1f94c4f966f6758d1b8d5614862753a9bd is restarting, wait until the container is running
[2025-02-21T22:09:02.207+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-21T22:09:02.220+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T22:09:02.223+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=gold_data_dag, task_id=say_hello, execution_date=20250221T220853, start_date=20250221T220901, end_date=20250221T220902
[2025-02-21T22:09:02.235+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 9 for task say_hello (Bash command failed. The command returned a non-zero exit code 1.; 181)
[2025-02-21T22:09:02.250+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-21T22:09:02.267+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
