[2025-02-25T09:48:43.390+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-25T09:48:43.575+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-25T09:48:43.596+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-25T09:48:43.799+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-04 00:00:00+00:00
[2025-02-25T09:48:43.864+0000] {standard_task_runner.py:57} INFO - Started process 330 to run task
[2025-02-25T09:48:43.891+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '47', '--raw', '--subdir', 'DAGS_FOLDER/test_hello.py', '--cfg-path', '/tmp/tmpihbu7l44']
[2025-02-25T09:48:43.951+0000] {standard_task_runner.py:85} INFO - Job 47: Subtask store_raw_data_in_hdfs
[2025-02-25T09:48:44.439+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [running]> on host 6dbd75e48aaa
[2025-02-25T09:48:44.955+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-02-25T09:49:37.880+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-25T09:49:38.057+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250104T000000, start_date=20250225T094843, end_date=20250225T094938
[2025-02-25T09:49:38.288+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-25T09:49:38.574+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:10:53.941+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-26T20:10:53.968+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-26T20:10:53.973+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:10:54.128+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-04 00:00:00+00:00
[2025-02-26T20:10:54.153+0000] {standard_task_runner.py:57} INFO - Started process 521 to run task
[2025-02-26T20:10:54.194+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '55', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpx_vpady1']
[2025-02-26T20:10:54.212+0000] {standard_task_runner.py:85} INFO - Job 55: Subtask store_raw_data_in_hdfs
[2025-02-26T20:10:54.485+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [running]> on host e304e68c626e
[2025-02-26T20:10:54.822+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-02-26T20:10:54.861+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 84, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-26T20:10:54.941+0000] {taskinstance.py:1400} INFO - Marking task as UP_FOR_RETRY. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250104T000000, start_date=20250226T201053, end_date=20250226T201054
[2025-02-26T20:10:54.989+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 55 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 521)
[2025-02-26T20:10:55.061+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:10:55.396+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:30:23.404+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-26T20:30:23.471+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-26T20:30:23.478+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:30:23.909+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-04 00:00:00+00:00
[2025-02-26T20:30:23.964+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '171', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpge5j7pth']
[2025-02-26T20:30:23.982+0000] {standard_task_runner.py:85} INFO - Job 171: Subtask store_raw_data_in_hdfs
[2025-02-26T20:30:23.972+0000] {standard_task_runner.py:57} INFO - Started process 1724 to run task
[2025-02-26T20:30:24.221+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [running]> on host c96a1011f5a3
[2025-02-26T20:30:24.569+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-02-26T20:30:58.180+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:30:58.237+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250104T000000, start_date=20250226T203023, end_date=20250226T203058
[2025-02-26T20:30:58.389+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:30:58.459+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:40:08.722+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-26T20:40:08.778+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-26T20:40:08.781+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2025-02-26T20:40:08.828+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-04 00:00:00+00:00
[2025-02-26T20:40:08.854+0000] {standard_task_runner.py:57} INFO - Started process 1112 to run task
[2025-02-26T20:40:08.873+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '283', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpdmo7pdiu']
[2025-02-26T20:40:08.886+0000] {standard_task_runner.py:85} INFO - Job 283: Subtask store_raw_data_in_hdfs
[2025-02-26T20:40:09.258+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:40:10.258+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-02-26T20:40:10.857+0000] {python.py:194} INFO - Done. Returned value was: None
[2025-02-26T20:40:10.892+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250104T000000, start_date=20250226T204008, end_date=20250226T204010
[2025-02-26T20:40:10.981+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-02-26T20:40:11.062+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2025-02-27T14:55:16.947+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-27T14:55:16.998+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [queued]>
[2025-02-27T14:55:16.999+0000] {taskinstance.py:1359} INFO - Starting attempt 1 of 1
[2025-02-27T14:55:17.089+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): store_raw_data_in_hdfs> on 2025-01-04 00:00:00+00:00
[2025-02-27T14:55:17.134+0000] {standard_task_runner.py:57} INFO - Started process 259 to run task
[2025-02-27T14:55:17.150+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'store_raw_data_in_hdfs', 'scheduled__2025-01-04T00:00:00+00:00', '--job-id', '20', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpmwrela8c']
[2025-02-27T14:55:17.166+0000] {standard_task_runner.py:85} INFO - Job 20: Subtask store_raw_data_in_hdfs
[2025-02-27T14:55:17.385+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.store_raw_data_in_hdfs scheduled__2025-01-04T00:00:00+00:00 [running]> on host a71f042480b6
[2025-02-27T14:55:17.842+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='store_raw_data_in_hdfs' AIRFLOW_CTX_EXECUTION_DATE='2025-01-04T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-04T00:00:00+00:00'
[2025-02-27T14:55:17.919+0000] {taskinstance.py:1935} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/pipeline.py", line 82, in store_raw_data_in_hdfs
    with open(local_file, 'w') as f:
PermissionError: [Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'
[2025-02-27T14:55:18.026+0000] {taskinstance.py:1398} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=store_raw_data_in_hdfs, execution_date=20250104T000000, start_date=20250227T145516, end_date=20250227T145518
[2025-02-27T14:55:18.224+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 20 for task store_raw_data_in_hdfs ([Errno 13] Permission denied: '/mnt/hadoop_data/yfinance_raw.json'; 259)
[2025-02-27T14:55:18.337+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-27T14:55:18.458+0000] {taskinstance.py:2776} INFO - 0 downstream tasks scheduled from follow-on schedule check
