[2025-02-26T20:23:54.791+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-02-26T20:23:54.802+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-02-26T20:23:54.803+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-26T20:23:54.822+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce> on 2025-01-06 00:00:00+00:00
[2025-02-26T20:23:54.828+0000] {standard_task_runner.py:57} INFO - Started process 873 to run task
[2025-02-26T20:23:54.832+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'run_mapreduce', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '100', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpfx13kkpg']
[2025-02-26T20:23:54.836+0000] {standard_task_runner.py:85} INFO - Job 100: Subtask run_mapreduce
[2025-02-26T20:23:54.896+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [running]> on host c96a1011f5a3
[2025-02-26T20:23:54.980+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-02-26T20:23:54.984+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T20:23:54.985+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i -u root namenode bash -c \'         cd /tmp &&         cp /mnt/hadoop_data/mapreduce/mapper.py . &&         cp /mnt/hadoop_data/mapreduce/reducer.py . &&         chmod +x mapper.py reducer.py &&         hdfs dfs -rm -r hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06 || true &&         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -files mapper.py,reducer.py         -mapper "python mapper.py"         -reducer "python reducer.py"         -input hdfs:///user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=06/yfinance_raw.json         -output hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06\'\n        ']
[2025-02-26T20:23:54.997+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T20:23:56.837+0000] {subprocess.py:93} INFO - rm: `hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06': No such file or directory
[2025-02-26T20:23:58.314+0000] {subprocess.py:93} INFO - 2025-02-26 20:23:58,312 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-26T20:23:58.428+0000] {subprocess.py:93} INFO - 2025-02-26 20:23:58,426 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-26T20:23:58.429+0000] {subprocess.py:93} INFO - 2025-02-26 20:23:58,426 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-26T20:23:58.444+0000] {subprocess.py:93} INFO - 2025-02-26 20:23:58,442 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-26T20:23:58.723+0000] {subprocess.py:93} INFO - 2025-02-26 20:23:58,722 INFO mapreduce.JobSubmitter: Cleaning up the staging area file:/tmp/hadoop/mapred/staging/root423316143/.staging/job_local423316143_0001
[2025-02-26T20:23:58.724+0000] {subprocess.py:93} INFO - 2025-02-26 20:23:58,723 ERROR streaming.StreamJob: Error Launching job : Input path does not exist: hdfs:/user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=06/yfinance_raw.json
[2025-02-26T20:23:58.725+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-26T20:23:59.208+0000] {subprocess.py:97} INFO - Command exited with return code 5
[2025-02-26T20:23:59.221+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-26T20:23:59.225+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=run_mapreduce, execution_date=20250106T000000, start_date=20250226T202354, end_date=20250226T202359
[2025-02-26T20:23:59.241+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 100 for task run_mapreduce (Bash command failed. The command returned a non-zero exit code 5.; 873)
[2025-02-26T20:23:59.697+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:23:59.739+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:37:26.038+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-02-26T20:37:26.080+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-02-26T20:37:26.089+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-26T20:37:26.175+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce> on 2025-01-06 00:00:00+00:00
[2025-02-26T20:37:26.191+0000] {standard_task_runner.py:57} INFO - Started process 244 to run task
[2025-02-26T20:37:26.214+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'run_mapreduce', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '202', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpazyrnyon']
[2025-02-26T20:37:26.228+0000] {standard_task_runner.py:85} INFO - Job 202: Subtask run_mapreduce
[2025-02-26T20:37:26.557+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:37:26.959+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-02-26T20:37:26.971+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T20:37:26.974+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i -u root namenode bash -c \'         cd /tmp &&         cp /mnt/hadoop_data/mapreduce/mapper.py . &&         cp /mnt/hadoop_data/mapreduce/reducer.py . &&         chmod +x mapper.py reducer.py &&         hdfs dfs -rm -r hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06 || true &&         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -files mapper.py,reducer.py         -mapper "python mapper.py"         -reducer "python reducer.py"         -input hdfs:///user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=06/yfinance_raw.json         -output hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06\'\n        ']
[2025-02-26T20:37:27.068+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T20:37:45.160+0000] {subprocess.py:93} INFO - Deleted hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06
[2025-02-26T20:38:02.954+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:02,938 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-26T20:38:03.150+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:03,148 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-26T20:38:03.153+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:03,149 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-26T20:38:03.285+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:03,281 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-26T20:38:10.502+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:10,499 INFO mapred.FileInputFormat: Total input files to process : 1
[2025-02-26T20:38:13.581+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:13,570 INFO mapreduce.JobSubmitter: number of splits:1
[2025-02-26T20:38:17.829+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:17,821 INFO mapreduce.JobSubmitter: Submitting tokens for job: job_local1200563383_0001
[2025-02-26T20:38:17.838+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:17,826 INFO mapreduce.JobSubmitter: Executing with tokens: []
[2025-02-26T20:38:27.425+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:27,330 INFO mapred.LocalDistributedCacheManager: Localized file:/tmp/mapper.py as file:/tmp/hadoop-root/mapred/local/job_local1200563383_0001_e2a95579-c753-4673-8838-01ced852ec52/mapper.py
[2025-02-26T20:38:27.718+0000] {subprocess.py:93} INFO - 2025-02-26 20:38:27,702 INFO mapred.LocalDistributedCacheManager: Localized file:/tmp/reducer.py as file:/tmp/hadoop-root/mapred/local/job_local1200563383_0001_f0a4212a-16e9-4132-bda1-e3bdfeeb7715/reducer.py
[2025-02-26T20:38:45.252+0000] {subprocess.py:97} INFO - Command exited with return code 137
[2025-02-26T20:38:45.490+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 137.
[2025-02-26T20:38:45.556+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=run_mapreduce, execution_date=20250106T000000, start_date=20250226T203726, end_date=20250226T203845
[2025-02-26T20:38:45.741+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 202 for task run_mapreduce (Bash command failed. The command returned a non-zero exit code 137.; 244)
[2025-02-26T20:38:45.887+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:38:46.279+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-02-26T20:46:02.947+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-02-26T20:46:02.992+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [queued]>
[2025-02-26T20:46:03.001+0000] {taskinstance.py:1361} INFO - Starting attempt 2 of 2
[2025-02-26T20:46:03.093+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): run_mapreduce> on 2025-01-06 00:00:00+00:00
[2025-02-26T20:46:03.114+0000] {standard_task_runner.py:57} INFO - Started process 2801 to run task
[2025-02-26T20:46:03.128+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'yfinance_ingestion_dag', 'run_mapreduce', 'scheduled__2025-01-06T00:00:00+00:00', '--job-id', '397', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmpongvh5un']
[2025-02-26T20:46:03.134+0000] {standard_task_runner.py:85} INFO - Job 397: Subtask run_mapreduce
[2025-02-26T20:46:03.295+0000] {task_command.py:415} INFO - Running <TaskInstance: yfinance_ingestion_dag.run_mapreduce scheduled__2025-01-06T00:00:00+00:00 [running]> on host 3c0faf52b292
[2025-02-26T20:46:03.734+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='etudiant' AIRFLOW_CTX_DAG_ID='yfinance_ingestion_dag' AIRFLOW_CTX_TASK_ID='run_mapreduce' AIRFLOW_CTX_EXECUTION_DATE='2025-01-06T00:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2025-01-06T00:00:00+00:00'
[2025-02-26T20:46:03.745+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-26T20:46:03.756+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', '\n        docker exec -i -u root namenode bash -c \'         cd /tmp &&         cp /mnt/hadoop_data/mapreduce/mapper.py . &&         cp /mnt/hadoop_data/mapreduce/reducer.py . &&         chmod +x mapper.py reducer.py &&         hdfs dfs -rm -r hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06 || true &&         hadoop jar /opt/hadoop-3.2.1/share/hadoop/tools/lib/hadoop-streaming-3.2.1.jar         -files mapper.py,reducer.py         -mapper "python mapper.py"         -reducer "python reducer.py"         -input hdfs:///user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=06/yfinance_raw.json         -output hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06\'\n        ']
[2025-02-26T20:46:03.874+0000] {subprocess.py:86} INFO - Output:
[2025-02-26T20:46:11.351+0000] {subprocess.py:93} INFO - rm: `hdfs:///user/etudiant/crypto/processed/YYYY=2025/MM=01/DD=06': No such file or directory
[2025-02-26T20:46:19.412+0000] {subprocess.py:93} INFO - 2025-02-26 20:46:19,401 INFO impl.MetricsConfig: Loaded properties from hadoop-metrics2.properties
[2025-02-26T20:46:19.542+0000] {subprocess.py:93} INFO - 2025-02-26 20:46:19,538 INFO impl.MetricsSystemImpl: Scheduled Metric snapshot period at 10 second(s).
[2025-02-26T20:46:19.550+0000] {subprocess.py:93} INFO - 2025-02-26 20:46:19,541 INFO impl.MetricsSystemImpl: JobTracker metrics system started
[2025-02-26T20:46:19.644+0000] {subprocess.py:93} INFO - 2025-02-26 20:46:19,633 WARN impl.MetricsSystemImpl: JobTracker metrics system already initialized!
[2025-02-26T20:46:20.466+0000] {subprocess.py:93} INFO - 2025-02-26 20:46:20,465 INFO mapreduce.JobSubmitter: Cleaning up the staging area file:/tmp/hadoop/mapred/staging/root83085089/.staging/job_local83085089_0001
[2025-02-26T20:46:20.470+0000] {subprocess.py:93} INFO - 2025-02-26 20:46:20,468 ERROR streaming.StreamJob: Error Launching job : Input path does not exist: hdfs:/user/etudiant/crypto/raw/YYYY=2025/MM=01/DD=06/yfinance_raw.json
[2025-02-26T20:46:20.472+0000] {subprocess.py:93} INFO - Streaming Command Failed!
[2025-02-26T20:46:20.951+0000] {subprocess.py:97} INFO - Command exited with return code 5
[2025-02-26T20:46:20.974+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 5.
[2025-02-26T20:46:20.986+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=yfinance_ingestion_dag, task_id=run_mapreduce, execution_date=20250106T000000, start_date=20250226T204602, end_date=20250226T204620
[2025-02-26T20:46:21.022+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 397 for task run_mapreduce (Bash command failed. The command returned a non-zero exit code 5.; 2801)
[2025-02-26T20:46:21.067+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-26T20:46:21.126+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
