[2025-02-21T22:35:45.771+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: gold_data_dag.runer manual__2025-02-21T22:35:42.021156+00:00 [queued]>
[2025-02-21T22:35:45.782+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: gold_data_dag.runer manual__2025-02-21T22:35:42.021156+00:00 [queued]>
[2025-02-21T22:35:45.784+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2025-02-21T22:35:45.870+0000] {taskinstance.py:1382} INFO - Executing <Task(BashOperator): runer> on 2025-02-21 22:35:42.021156+00:00
[2025-02-21T22:35:45.874+0000] {standard_task_runner.py:57} INFO - Started process 89 to run task
[2025-02-21T22:35:45.878+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'gold_data_dag', 'runer', 'manual__2025-02-21T22:35:42.021156+00:00', '--job-id', '26', '--raw', '--subdir', 'DAGS_FOLDER/pipeline.py', '--cfg-path', '/tmp/tmp7vg8im2w']
[2025-02-21T22:35:45.882+0000] {standard_task_runner.py:85} INFO - Job 26: Subtask runer
[2025-02-21T22:35:45.942+0000] {task_command.py:415} INFO - Running <TaskInstance: gold_data_dag.runer manual__2025-02-21T22:35:42.021156+00:00 [running]> on host 7c80cef5d079
[2025-02-21T22:35:46.051+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='gold_data_dag' AIRFLOW_CTX_TASK_ID='runer' AIRFLOW_CTX_EXECUTION_DATE='2025-02-21T22:35:42.021156+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-02-21T22:35:42.021156+00:00'
[2025-02-21T22:35:46.053+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-02-21T22:35:46.054+0000] {subprocess.py:75} INFO - Running command: ['/bin/bash', '-c', 'docker run big_data_projet-scraper bash -c "python /app/scraper.py"']
[2025-02-21T22:35:46.065+0000] {subprocess.py:86} INFO - Output:
[2025-02-21T22:35:46.989+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-02-21T22:35:46.991+0000] {subprocess.py:93} INFO -   File "/app/scraper.py", line 1, in <module>
[2025-02-21T22:35:46.991+0000] {subprocess.py:93} INFO -     import yfinance as yf
[2025-02-21T22:35:46.992+0000] {subprocess.py:93} INFO - ModuleNotFoundError: No module named 'yfinance'
[2025-02-21T22:35:47.501+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-02-21T22:35:47.531+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 210, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-02-21T22:35:47.551+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=gold_data_dag, task_id=runer, execution_date=20250221T223542, start_date=20250221T223545, end_date=20250221T223547
[2025-02-21T22:35:47.607+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 26 for task runer (Bash command failed. The command returned a non-zero exit code 1.; 89)
[2025-02-21T22:35:47.627+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2025-02-21T22:35:47.682+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
